# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20170711_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-publish',)},
        ),
    ]
