# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_category_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
    ]
