# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20170717_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
